version: '3.8'
services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recruitment-webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
