# config/services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Ładuj wszystkie klasy z src/
  App\:
    resource: '../src/*'
    exclude:
      - '../src/Kernel.php'
      - '../src/Entity'
      - '../src/Migrations'
      - '../src/Tests'
      - '../src/Resources'

  # Kontrolery jako serwisy
  App\Controller\:
    resource: '../src/Controller/'
    tags: ['controller.service_arguments']
